services:
  web:
    image: ghcr.io/cedar2025/xboard:new
    volumes:
      - ./:/www/
    environment:
      - docker=true
    network_mode: host
    command: php artisan octane:start --port=7001 --host=0.0.0.0
    restart: always
  horizon:
    image: ghcr.io/cedar2025/xboard:new
    volumes:
      - ./:/www/
    restart: always
    network_mode: host
    command: php artisan horizon
